---
name: Addon-JS
version: 1.1.1
slug: example
description: Plugin encargado de ejecutar scripts en node.js
url: https://github.com/ElFumao420/addon-js
codenotary: codenotary@frenck.dev
init: false
arch:
  - aarch64
  - amd64
options:
  log_level: info
  seconds_between_quotes: 5
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)
  seconds_between_quotes: int(1,120)
