---
name: Addon-JS
version: dev
slug: example
description: Example add-on by Community Home Assistant Add-ons
url: https://github.com/ElFumao420/addon-js
codenotary: codenotary@frenck.dev
init: false
arch:
  - aarch64
  - amd64
options:
  log_level: info
  seconds_between_quotes: 5
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)
  seconds_between_quotes: int(1,120)
